CREATE TABLE egresos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  detalle VARCHAR(255) NOT NULL,
  forma_pago VARCHAR(100) NOT NULL,
  importe DECIMAL(12, 2) NOT NULL,
  fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
